import {
  BarChart3,
  Bell,
  BrainCircuit,
  CalendarDays,
  CheckCircle2,
  ClipboardCheck,
  Download,
  FileClock,
  LayoutDashboard,
  LogOut,
  Menu,
  QrCode,
  RefreshCw,
  Send,
  ShieldCheck,
  Users,
  X,
} from 'lucide-react';

export const BionisIcons = {
  dashboard: LayoutDashboard,
  verify: ClipboardCheck,
  checkIn: QrCode,
  events: CalendarDays,
  invitations: Send,
  announcements: Bell,
  analysis: BrainCircuit,
  export: Download,
  audit: FileClock,
  access: ShieldCheck,
  users: Users,
  confirmed: CheckCircle2,
  chart: BarChart3,
  refresh: RefreshCw,
  logout: LogOut,
  menu: Menu,
  close: X,
};
