EVENT_CATALOG = [
    {"id": "ctf", "name": "NULL CORE 2.0 CTF", "category": "tech", "duration_minutes": 180, "is_ctf": True, "fee": 150, "teamMin": 2, "teamMax": 3, "detailsComplete": True, "status": "open", "venue": "CSE Cyber Lab 2", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "bug-hunt", "name": "Bug Hunt", "category": "tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 1, "teamMax": 1, "detailsComplete": True, "status": "open", "venue": "Cyber Lab 1", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "prompt-heist", "name": "Prompt Heist", "category": "tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 1, "teamMax": 2, "detailsComplete": True, "status": "open", "venue": "AI Innovation Lab", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "secure-x-vibecode", "name": "Secure X Vibe Coding", "category": "tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 1, "teamMax": 2, "detailsComplete": True, "status": "open", "venue": "IoT Research Lab", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "ignite", "name": "IGNITE", "category": "tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 3, "detailsComplete": True, "status": "open", "venue": "Main Auditorium", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "mystery-hunt", "name": "Mystery Hunt", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Seminar Hall A", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "tune-trap", "name": "Tune Trap", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Open Air Theatre", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "ipl-bidverse", "name": "IPL Bidverse", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Mini Auditorium", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "playground-of-hackers", "name": "Playground of Hackers", "category": "workshop", "duration_minutes": 120, "is_ctf": False, "fee": 150, "teamMin": 1, "teamMax": 1, "detailsComplete": True, "status": "open", "venue": "Cyber Security Lab 2", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    # Aliases for backwards compatibility
    {"id": "art-of-hacking", "name": "Playground of Hackers", "category": "workshop", "duration_minutes": 120, "is_ctf": False, "fee": 150, "teamMin": 1, "teamMax": 1, "detailsComplete": True, "status": "open", "venue": "Cyber Security Lab 2", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "crime-investigation", "name": "Mystery Hunt", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Seminar Hall A", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "tune-tracker", "name": "Tune Trap", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Open Air Theatre", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "ipl-auction-2026", "name": "IPL Bidverse", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Mini Auditorium", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
    {"id": "ipl-auction", "name": "IPL Bidverse", "category": "non-tech", "duration_minutes": 180, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Mini Auditorium", "date": "2026-09-26", "time": "10:00", "gate": "VEC Gate 1"},
]

EVENTS_BY_ID = {event["id"]: event for event in EVENT_CATALOG}
