EVENT_CATALOG = [
    {"id": "crime-investigation", "name": "Crime Investigation", "category": "non-tech", "duration_minutes": 90, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Seminar Hall A", "date": "2026-09-26", "time": "11:30", "gate": "VEC Gate 1"},
    {"id": "bug-bounty-2026", "name": "Bug Bounty 2026", "category": "tech", "duration_minutes": 120, "is_ctf": False, "fee": 200, "teamMin": 1, "teamMax": 1, "detailsComplete": True, "status": "open", "venue": "Cyber Lab 1", "date": "2026-09-26", "time": "09:30", "gate": "VEC Gate 1"},
    {"id": "ctf", "name": "CTF", "category": "tech", "duration_minutes": 180, "is_ctf": True, "fee": 200, "teamMin": 2, "teamMax": 3, "detailsComplete": True, "status": "open", "venue": "CSE Cyber Lab 2", "date": "2026-09-26", "time": "09:30", "gate": "VEC Gate 1"},
    {"id": "secure-x-vibecode", "name": "Secure X Vibe Coding", "category": "tech", "duration_minutes": 120, "is_ctf": False, "fee": 200, "teamMin": 1, "teamMax": 2, "detailsComplete": True, "status": "open", "venue": "IoT Research Lab", "date": "2026-09-26", "time": "09:30", "gate": "VEC Gate 1"},
    {"id": "ppt-ideathon", "name": "PPT Ideathon", "category": "tech", "duration_minutes": 90, "is_ctf": False, "fee": 200, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Main Auditorium", "date": "2026-09-26", "time": "09:30", "gate": "VEC Gate 1"},
    {"id": "ipl-auction-2026", "name": "IPL Auction 2026", "category": "non-tech", "duration_minutes": 90, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Mini Auditorium", "date": "2026-09-26", "time": "11:30", "gate": "VEC Gate 1"},
    {"id": "tune-tracker", "name": "Tune Tracker", "category": "non-tech", "duration_minutes": 60, "is_ctf": False, "fee": 150, "teamMin": 2, "teamMax": 4, "detailsComplete": True, "status": "open", "venue": "Open Air Theatre", "date": "2026-09-26", "time": "11:30", "gate": "VEC Gate 1"},
    {"id": "ai-jail-break", "name": "AI Jail Break", "category": "tech", "duration_minutes": 90, "is_ctf": False, "fee": 200, "teamMin": 2, "teamMax": 2, "detailsComplete": True, "status": "open", "venue": "AI Innovation Lab", "date": "2026-09-26", "time": "09:30", "gate": "VEC Gate 1"},
]

EVENTS_BY_ID = {event["id"]: event for event in EVENT_CATALOG}
